In [ ]:
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
#!pip install ai4bharat-transliteration

In [ ]:
#from ai4bharat.transliteration import XlitEngine

In [ ]:
import pandas as pd

In [ ]:
#df = pd.read_csv('/content/gdrive/My Drive/img data/tweets-train_pp_12114_transliterated.csv', sep=',')

In [ ]:
#df['tweet'][0]

In [ ]:
#transliterator = XlitEngine(src_script_type="indic", beam_width=1, rescore=False)
#transliterator = XlitEngine(src_script_type="indic", beam_width=1)

In [ ]:
'''  for i in range(12000,12115):
    df['tweet'][i] = transliterator.translit_sentence(df['tweet'][i],lang_code="mr")
    print(i)'''

'  for i in range(12000,12115):\n    df[\'tweet\'][i] = transliterator.translit_sentence(df[\'tweet\'][i],lang_code="mr")\n    print(i)'

In [ ]:
#df['tweet'][:]

In [ ]:
#text = df['tweet'][0:12114]
#text = ['ज्येष्ठ पत्रकार अनंत दीक्षित यांच्या निधनाचे वृत्त दुखद आहे']

In [ ]:
#text[12113]

In [ ]:
#df.to_csv('/content/gdrive/My Drive/img data/tweets-train_pp_12114_transliterated.csv')

In [ ]:
#h

In [ ]:
#sentence = ' आपला समाज खूप मोठा आहे त्यात अनेक घटक अंतर्भूत आहेत यातील दिव्यांग हा एक घटक जो शारीरिकदृष्ट्या कमकुवत आहे त्याच्याकडे समाजाचे दुर्लक्ष होतेय त्यामुळे सरकारने अशा व्यक्तींसाठी उपक्रम राबवून त्यांना समाजात सन्मानाने जगता येईल याकडे लक्ष देण्याची गरज आहे'

In [ ]:
#ab

In [ ]:
!pip install transformers
!pip install -U tensorflow-addons

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 80.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 21.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 51.1 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 54.6 MB/s eta 0:00:00


In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from tensorflow.keras import regularizers
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import tensorflow as tf
import tensorflow_addons as tfa
from transformers import BertTokenizer,TFBertForSequenceClassification,AutoTokenizer,TFAutoModelForSequenceClassification

In [ ]:
#adj_mat = np.load('/content/gdrive/My Drive/dataset/adj_matrix.npy')

In [ ]:
#df = pd.read_csv('F:\\BTP\\bert test\\tweets-train_pp_stop_012.csv', sep=',')
#df2 = pd.read_csv('F:\\BTP\\bert test\\tweets-valid_pp_012.csv', sep=',')

In [ ]:
'''import pandas as pd
import json
import requests
from urllib.parse import  quote #indicnlplibrary'''

'import pandas as pd\nimport json\nimport requests\nfrom urllib.parse import  quote #indicnlplibrary'

In [ ]:
#df = pd.read_csv('/content/gdrive/My Drive/img data/tweets-train_pp_img_tweets.csv', sep=',')
#df = pd.read_csv('/content/gdrive/MyDrive/dataset/tweets-train_pp_24228_augmented_backtrans_pp.csv', sep=',')
df = pd.read_csv('/content/gdrive/MyDrive/dataset/tweets-train_mar_emo_insrt2.csv', sep=',')
#df = pd.read_csv('/content/gdrive/My Drive/dataset/tweets-train_pp_stop_012.csv', sep=',')
df2 = pd.read_csv('/content/gdrive/My Drive/dataset/tweets-test_mar_emo_insrt2.csv', sep=',')
df3 = pd.read_csv('/content/gdrive/My Drive/dataset/tweets-val_mar_emo_insrt2.csv', sep=',')

In [ ]:
#df['tweet'][0]

In [ ]:
#df['tweet'][0]

In [ ]:
'''
The sentiment labels are:

0 - negative
1  - neutral
2  - positive
'''

'\nThe sentiment labels are:\n\n0 - negative\n1  - neutral\n2  - positive\n'

In [ ]:
#tokenizer = BertTokenizer.from_pretrained('google/muril-base-cased',lang='mr')
#tokenizer = BertTokenizer.from_pretrained('google/muril-base-cased')
tokenizer = AutoTokenizer.from_pretrained('l3cube-pune/marathi-roberta',from_pt=True) #maharoberta
#tokenizer = AutoTokenizer.from_pretrained("l3cube-pune/MarathiSentiment")
#tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)
#tokenizer = AutoTokenizer.from_pretrained('xlm-roberta-base',lang='mr') #xlm

In [ ]:
#df['label'].value_counts()

In [ ]:
token = tokenizer.encode_plus(
    df['tweet'].iloc[0], 
    max_length=100, 
    truncation=True, 
    padding='max_length',
    #pad_to_max_length = True, 
    add_special_tokens=True,
    return_tensors='tf'
)
#token.input_ids

In [ ]:
token_emo = tokenizer.encode_plus(
    df['bertlabel'].iloc[0], 
    max_length=5, 
    truncation=True, 
    padding='max_length',
    #pad_to_max_length = True, 
    add_special_tokens=True,
    return_tensors='tf'
)

In [ ]:
X_input_ids = np.zeros((len(df), 100))
X_attn_masks = np.zeros((len(df), 100))
X_input_ids_val = np.zeros((len(df2), 100))
X_attn_masks_val = np.zeros((len(df2), 100))
X_input_ids_test = np.zeros((len(df3), 100))
X_attn_masks_test = np.zeros((len(df3), 100))

In [ ]:
X_input_ids_emo = np.zeros((len(df), 3))
X_attn_masks_emo = np.zeros((len(df), 3))
X_input_ids_val_emo = np.zeros((len(df2), 3))
X_attn_masks_val_emo = np.zeros((len(df2), 3))
X_input_ids_test_emo = np.zeros((len(df3), 3))
X_attn_masks_test_emo = np.zeros((len(df3), 3))

In [ ]:
x2 = np.load('/content/gdrive/My Drive/image download/features_3_train.npy')
x3 = np.load('/content/gdrive/My Drive/image download/features_3_test.npy')
x4 = np.load('/content/gdrive/My Drive/image download/features_3_valid.npy')

In [ ]:
X_img_features = np.zeros((len(df), 1000))
X_img_features_val = np.zeros((len(df2), 1000))
X_img_features_test = np.zeros((len(df3), 1000))

In [ ]:
for i in range(len(df)):
  X_img_features[i] = x2[i]
for i in range(len(df2)):
  X_img_features_val[i] = x3[i]
for i in range(len(df3)):
  X_img_features_test[i] = x4[i]

In [ ]:
#np.shape(X_img_features)

In [ ]:
np.shape(X_input_ids)

(24228, 100)

In [ ]:
def generate_training_data(df, ids, masks, tokenizer):
    for i, text in tqdm(enumerate(df['tweet'])):
        tokenized_text = tokenizer.encode_plus(
            text,
            max_length=100, 
            truncation=True, 
            padding='max_length', 
            add_special_tokens=True,
            return_tensors='tf'
        )
        ids[i, :] = tokenized_text.input_ids
        masks[i, :] = tokenized_text.attention_mask
    return ids, masks

In [ ]:
def generate_training_data_emo(df, ids, masks, tokenizer):
    for i, text in tqdm(enumerate(df['bertlabel'])):
        tokenized_text = tokenizer.encode_plus(
            text,
            max_length=3, 
            truncation=True, 
            padding='max_length', 
            add_special_tokens=True,
            return_tensors='tf'
        )
        ids[i, :] = tokenized_text.input_ids
        masks[i, :] = tokenized_text.attention_mask
    return ids, masks

In [ ]:
df['tweet'][23101] = df['tweet'][23101-12114]

<ipython-input-39-abf2e1054a31>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tweet'][23101] = df['tweet'][23101-12114]


In [ ]:
X_input_ids, X_attn_masks = generate_training_data(df, X_input_ids, X_attn_masks, tokenizer)

0it [00:00, ?it/s]

In [ ]:
df['tweet'][0]

'दुख ज्येष्ठ पत्रकार अनंत दीक्षित यांच्या निधनाचे वृत्त दुखद आहे चार दशकं त्यांनी आपल्या परखड लेखणीने पत्रकारितेत अमूल्य योगदान दिले दीक्षित यांच्या मार्गदर्शनाखाली पत्रकारांची पिढी घडली अनंत दीक्षित यांना भावपूर्ण श्रद्धांजली आम्ही त्यांच्या परिवाराच्या दुखात सहभागी आहोत दुख'

In [ ]:
X_input_ids[0]

array([0.00000e+00, 7.58530e+04, 1.73780e+05, 3.04650e+04, 2.30125e+05,
       1.00250e+04, 8.26920e+04, 2.25820e+04, 7.84090e+04, 9.60300e+03,
       1.35870e+05, 7.58530e+04, 3.04400e+03, 1.38300e+03, 1.50010e+04,
       1.10726e+05, 8.38000e+02, 3.69910e+04, 1.73750e+04, 9.68000e+02,
       7.50500e+03, 2.43500e+03, 1.18110e+04, 1.30410e+04, 1.18700e+03,
       3.04650e+04, 3.28200e+03, 2.87220e+04, 2.13900e+03, 1.88779e+05,
       9.70100e+04, 5.94490e+04, 1.00250e+04, 8.26920e+04, 2.25820e+04,
       2.00014e+05, 1.75211e+05, 3.04650e+04, 2.11650e+04, 1.40610e+04,
       7.50770e+04, 5.77690e+04, 2.41600e+03, 2.30125e+05, 1.00250e+04,
       8.26920e+04, 6.50230e+04, 3.32180e+04, 3.87510e+04, 1.34278e+05,
       3.68600e+04, 2.41600e+03, 4.59800e+04, 3.21370e+04, 2.22030e+04,
       7.26100e+03, 7.58530e+04, 2.53500e+03, 5.34030e+04, 1.44938e+05,
       7.58530e+04, 2.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00,
       1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00, 1.000

In [ ]:
X_input_ids_val, X_attn_masks_val = generate_training_data(df2, X_input_ids_val, X_attn_masks_val, tokenizer)

0it [00:00, ?it/s]

In [ ]:
X_input_ids_test, X_attn_masks_test = generate_training_data(df3, X_input_ids_test, X_attn_masks_test, tokenizer)

0it [00:00, ?it/s]

In [ ]:
X_input_ids_test_emo, X_attn_masks_test_emo = generate_training_data_emo(df3, X_input_ids_test_emo, X_attn_masks_test_emo, tokenizer)

0it [00:00, ?it/s]

In [ ]:
X_input_ids_val_emo, X_attn_masks_val_emo = generate_training_data_emo(df2, X_input_ids_val_emo, X_attn_masks_val_emo, tokenizer)

0it [00:00, ?it/s]

In [ ]:
X_input_ids_emo, X_attn_masks_emo = generate_training_data_emo(df, X_input_ids_emo, X_attn_masks_emo, tokenizer)

0it [00:00, ?it/s]

In [ ]:
labels = np.zeros((len(df), 3))

In [ ]:
labels_val = np.zeros((len(df2), 3))

In [ ]:
labels_test = np.zeros((len(df3), 3))

In [ ]:
#labels.shape

In [ ]:
labels_emo = np.zeros((len(df), 3))

In [ ]:
labels_val_emo = np.zeros((len(df2), 3))

In [ ]:
labels_test_emo = np.zeros((len(df3), 3))

In [ ]:
labels[np.arange(len(df)), df['label'].values] = 1 # one-hot encoded target tensor

In [ ]:
labels_val[np.arange(len(df2)), df2['label'].values] = 1 # one-hot encoded target tensor

In [ ]:
labels_test[np.arange(len(df3)), df3['label'].values] = 1 # one-hot encoded target tensor

In [ ]:
labels

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
labels_emo[np.arange(len(df)), df['label'].values] = 1 # one-hot encoded target tensor

In [ ]:
labels_val_emo[np.arange(len(df2)), df2['label'].values] = 1 # one-hot encoded target tensor

In [ ]:
labels_test_emo[np.arange(len(df3)), df3['label'].values] = 1 # one-hot encoded target tensor

In [ ]:
# creating a data pipeline using tensorflow dataset utility, creates batches of data for easy loading...
dataset = tf.data.Dataset.from_tensor_slices((X_input_ids, X_attn_masks, labels))
# dataset = tf.data.Dataset.from_tensor_slices((X_input_ids, X_attn_masks, X_img_features,labels))

In [ ]:
dataset_val = tf.data.Dataset.from_tensor_slices((X_input_ids_val, X_attn_masks_val, labels_val))
# dataset_val = tf.data.Dataset.from_tensor_slices((X_input_ids_val, X_attn_masks_val, X_img_features_val,labels_val))

In [ ]:
dataset_test = tf.data.Dataset.from_tensor_slices((X_input_ids_test, X_attn_masks_test, labels_test))
# dataset_test = tf.data.Dataset.from_tensor_slices((X_input_ids_test, X_attn_masks_test, X_img_features_test,labels_test))

In [ ]:
# creating a data pipeline using tensorflow dataset utility, creates batches of data for easy loading...
# dataset = tf.data.Dataset.from_tensor_slices((X_input_ids, X_attn_masks, labels))
# dataset_emo = tf.data.Dataset.from_tensor_slices((X_input_ids, X_attn_masks,X_input_ids_emo, X_attn_masks_emo, X_img_features,labels_emo))

In [ ]:
# dataset_val = tf.data.Dataset.from_tensor_slices((X_input_ids_val, X_attn_masks_val, labels_val))
# dataset_val_emo = tf.data.Dataset.from_tensor_slices((X_input_ids_val, X_attn_masks_val,X_input_ids_val_emo, X_attn_masks_val_emo, X_img_features_val,labels_val_emo))

In [ ]:
# dataset_test = tf.data.Dataset.from_tensor_slices((X_input_ids_test, X_attn_masks_test, labels_test))
# dataset_test_emo = tf.data.Dataset.from_tensor_slices((X_input_ids_test, X_attn_masks_test,X_input_ids_test_emo, X_attn_masks_test_emo, X_img_features_test,labels_test_emo))

In [ ]:
#dataset.take(1) # one sample data

In [ ]:
# def SentimentDatasetMapFunction(input_ids, attn_masks, img_features, labels):
#     return {
#         'input_ids': input_ids,
#         'attention_mask': attn_masks,
#         'img_feats': img_features
#     }, labels

def SentimentDatasetMapFunction(input_ids, attn_masks, labels):
    return {
        'input_ids': input_ids,
        'attention_mask': attn_masks
    }, labels

In [ ]:
def SentimentDatasetMapFunction_emo(input_ids, attn_masks, input_ids_emo, attn_masks_emo,img_features, labels):
    return {
        'input_ids': input_ids,
        'attention_mask': attn_masks,
        'input_ids_emo': input_ids_emo,
        'attention_mask_emo': attn_masks_emo,
        'img_feats': img_features
    }, labels

# def SentimentDatasetMapFunction(input_ids, attn_masks, labels):
#     return {
#         'input_ids': input_ids,
#         'attention_mask': attn_masks
#     }, labels

In [ ]:
dataset = dataset.map(SentimentDatasetMapFunction) # converting to required format for tensorflow dataset

In [ ]:
dataset_val = dataset_val.map(SentimentDatasetMapFunction) # converting to required format for tensorflow dataset

In [ ]:
dataset_test = dataset_test.map(SentimentDatasetMapFunction) # converting to required format for tensorflow dataset

In [ ]:
# dataset = dataset_emo.map(SentimentDatasetMapFunction_emo) # converting to required format for tensorflow dataset

In [ ]:
# dataset_val = dataset_val_emo.map(SentimentDatasetMapFunction_emo) # converting to required format for tensorflow dataset

In [ ]:
# dataset_test = dataset_test_emo.map(SentimentDatasetMapFunction_emo) # converting to required format for tensorflow dataset

In [ ]:
dataset.take(1)

<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(100,), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(100,), dtype=tf.float64, name=None), 'input_ids_emo': TensorSpec(shape=(3,), dtype=tf.float64, name=None), 'attention_mask_emo': TensorSpec(shape=(3,), dtype=tf.float64, name=None), 'img_feats': TensorSpec(shape=(1000,), dtype=tf.float64, name=None)}, TensorSpec(shape=(3,), dtype=tf.float64, name=None))>

In [ ]:
batch_size_def = 6

In [ ]:
dataset = dataset.batch(batch_size_def, drop_remainder=True) # batch size, drop any left out tensor

In [ ]:
dataset_val = dataset_val.batch(batch_size_def, drop_remainder=True) # batch size, drop any left out tensor

In [ ]:
dataset_test = dataset_test.batch(batch_size_def, drop_remainder=True) # batch size, drop any left out tensor

In [ ]:
dataset.take(1)

<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(6, 100), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(6, 100), dtype=tf.float64, name=None), 'input_ids_emo': TensorSpec(shape=(6, 3), dtype=tf.float64, name=None), 'attention_mask_emo': TensorSpec(shape=(6, 3), dtype=tf.float64, name=None), 'img_feats': TensorSpec(shape=(6, 1000), dtype=tf.float64, name=None)}, TensorSpec(shape=(6, 3), dtype=tf.float64, name=None))>

In [ ]:
p = 0.85
#p=1
train_size = int((len(df)//batch_size_def*p)) # for each 6 batch of data we will have len(df)//6 samples, take 85% of that for train.

In [ ]:
##train_size
train_dataset = dataset.take(train_size)
test_dataset = train_dataset.take(int((1-p)*train_size)) #15% test
val_dataset = dataset_val
test_dataset_2 = dataset_test
train_dataset = train_dataset.skip(int((1-p)*train_size)) #70% train

In [ ]:
test_dataset_2 = dataset_test

In [ ]:
# MODEL
#model = TFBertForSequenceClassification.from_pretrained('google/muril-base-cased',from_pt=True) # bert base model with pretrained weights 
model = TFAutoModelForSequenceClassification.from_pretrained('l3cube-pune/marathi-roberta',from_pt=True) # maharoberta
#model = TFAutoModelForSequenceClassification.from_pretrained("l3cube-pune/MarathiSentiment")
#model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased')
#model = TFAutoModelForSequenceClassification.from_pretrained('xlm-roberta-base',from_pt=True) # bert base model with pretrained weights #xlm

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFXLMRobertaForSequenceClassification: ['roberta.embeddings.position_ids']
- This IS expected if you are initializing TFXLMRobertaForSequenceClassification from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFXLMRobertaForSequenceClassification from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
Some weights or buffers of the TF 2.0 model TFXLMRobertaForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it 

In [ ]:
#X_img_features

In [ ]:
# # defining 2 input layers for input_ids and attn_masks
# input_ids = tf.keras.layers.Input(shape=(100,), name='input_ids', dtype='int32')
# attn_masks = tf.keras.layers.Input(shape=(100,), name='attention_mask', dtype='int32')
# img_feats = tf.keras.layers.Input(shape=(1000,), name='img_feats', dtype='int32')

In [ ]:
# defining 2 input layers for input_ids and attn_masks
input_ids = tf.keras.layers.Input(shape=(100,), name='input_ids', dtype='int32')
attn_masks = tf.keras.layers.Input(shape=(100,), name='attention_mask', dtype='int32')
input_ids_emo = tf.keras.layers.Input(shape=(3,), name='input_ids_emo', dtype='int32')
attn_masks_emo = tf.keras.layers.Input(shape=(3,), name='attention_mask_emo', dtype='int32')
img_feats = tf.keras.layers.Input(shape=(1000,), name='img_feats', dtype='int32')

In [ ]:
print("balellllllllllllllllllllllllllll")
null_img = np.zeros((224,224,3))

balellllllllllllllllllllllllllll


In [ ]:
#img_feats

In [ ]:
!pip install sentencepiece #maharoberta

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 59.7 MB/s eta 0:00:00


In [ ]:
import sentencepiece #maharoberta

In [ ]:
from tensorflow.keras.layers import Layer
class GraphConvolution(Layer):
    """
    Simple GCN layer, similar to https://arxiv.org/abs/1609.02907
    """

    def __init__(self, in_features, out_features, bias=False, **kwargs):
        super(GraphConvolution, self).__init__(**kwargs)
        self.in_features = in_features
        self.out_features = out_features
        self.bias = bias


    def build(self, input_shape):
        self.w = self.add_weight(name='w',
                                   shape=(self.in_features, self.out_features),
                                   initializer='random_normal',
                                   trainable=True)
        if self.bias:
            # self.bias = Parameter(torch.Tensor(1, 1, out_features))
            self.b = self.add_weight(name='b',
                                       shape=(1, 1, self.out_features),
                                       initializer='random_normal',
                                       trainable=True)
        else:
            # self.register_parameter('bias', None)
            self.b = None
        super(GraphConvolution, self).build(input_shape)  # Be sure to call this somewhere!


    def call(self, x):
        inp = x[0]
        adj = x[1]
        support = K.dot(inp, self.w)
        output = K.dot(adj, support)
        if self.b is not None:
            return output + self.b
        else:
            return output

    def get_config(self):
        return super(GraphConvolution, self).get_config()

from tensorflow.keras.layers import MaxPool2D, LeakyReLU

def gen_A(num_classes, adj_matrix):
    _adj=adj_matrix * 0.25 /(adj_matrix.sum(0)+ 1e-6)
    _adj=_adj+np.identity(num_classes,np.int)
    return _adj

def gen_adj(A):
    D = tf.math.pow(A.sum(1), -0.5)
    D = tf.linalg.diag(D)
    p1 = tf.matmul(A, D)
    p1 = K.transpose(p1)
    adj = K.dot(p1, D)
    return adj

class GCNHashtag(Layer):

    def __init__(self, num_classes, adj_matrix, in_channel, **kwargs):
        super(GCNHashtag, self).__init__(**kwargs)
        self.num_classes = num_classes
        self.in_channel = in_channel

        self.pooling = MaxPool2D(14, 14)

        self.gc1 = GraphConvolution(in_channel, 1024)
        self.gc2 = GraphConvolution(1024, in_channel)
        self.relu = LeakyReLU(0.2)
        
        self.adj = gen_A(num_classes, adj_matrix)

    def build(self, input_shape):
        super(GCNHashtag, self).build(input_shape)  # Be sure to call this somewhere!

    def call(self, init_hashtag_matrix):
        adj = gen_adj(self.adj)
        x = self.gc1([init_hashtag_matrix, adj])
        x = self.relu(x)
        x = self.gc2([x, adj])
        return x

class PropagationModel(Layer):

    def __init__(self, adj_file, hashtag_num, embed_size, **kwargs):
        super(PropagationModel, self).__init__(**kwargs)
        self.adj_file = adj_file
        self.hashtag_num = hashtag_num
        self.embed_size = embed_size

        self.adj_matrix = np.load(self.adj_file).astype(float)
        self.gcnhashtag = GCNHashtag(self.hashtag_num, self.adj_matrix, self.embed_size)
        self.init_hashtag_matrix = np.random.rand(self.hashtag_num, self.embed_size)
        
    def build(self, input_shape):
        super(PropagationModel, self).build(input_shape)  # Be sure to call this somewhere!

    def call(self, inputs=None, ids=None):
        if inputs is None:
            hashtag_matrix = self.gcnhashtag(self.init_hashtag_matrix)
        else:
            # Work in Progress
            hashtag_matrix = self.gcnhashtag(inputs)
        self.hashtag_matrix = hashtag_matrix
        return hashtag_matrix
    
class HashtagEmbedding(Layer):

    def __init__(self, adj_file, hashtag_num, embed_size, **kwargs):
        super(HashtagEmbedding, self).__init__(**kwargs)        
        self.pm = PropagationModel(adj_file, hashtag_num, embed_size)

    def build(self, input_shape):
        super(HashtagEmbedding, self).build(input_shape)  # Be sure to call this somewhere!

    def call(self, ids, inputs=None):
        hashtag_matrix = self.pm(inputs, ids)
        return tf.gather(hashtag_matrix, indices=ids)


##When passing to main model(youcan change here)
#    if include_gcn_user:
 #       userEmbeddings = HashtagEmbedding(adj_file=adjMatrixPath2, hashtag_num=num_users, embed_size=embedding_size)

In [ ]:
#adj_mat = np.load('/content/gdrive/My Drive/dataset/adj_matrix.npy')

In [ ]:
#userEmbeddings = HashtagEmbedding(adj_file=adj_mat, hashtag_num=49795, embed_size=768)

In [ ]:
#A_adj = HashtagEmbedding(X_input_ids,1,768)

In [ ]:
#gcn1 = HashtagEmbedding()

In [ ]:
#attention3
from tensorflow.keras.layers import Layer
from keras import initializers as initializers, regularizers, constraints
from keras import backend as K

def dot_product(x, kernel):
    """
    Wrapper for dot product operation, in order to be compatible with both
    Theano and Tensorflow
    Args:
        x (): input
        kernel (): weights
    Returns:
    """
    if K.backend() == 'tensorflow':
        return K.squeeze(K.dot(x, K.expand_dims(kernel)), axis=-1)
    else:
        return K.dot(x, kernel)

class HierchacicalAttentionLayer(Layer):
    """
    Attention operation, with a context/query vector, for temporal data.
    Supports Masking.
    Follows the work of Yang et al. [https://www.cs.cmu.edu/~diyiy/docs/naacl16.pdf]
    "Hierarchical Attention Networks for Document Classification"
    by using a context vector to assist the attention
    # Input shape
        3D tensor with shape: `(samples, steps, features)`.
    # Output shape
        2D tensor with shape: `(samples, features)`.
    How to use:
    Just put it on top of an RNN Layer (GRU/LSTM/SimpleRNN) with return_sequences=True.
    The dimensions are inferred based on the output shape of the RNN.
    Note: The layer has been tested with Keras 2.0.6
    Example:
        model.add(LSTM(64, return_sequences=True))
        model.add(HierchacicalAttentionLayer())
        # next add a Dense layer (for classification/regression) or whatever...
    """
 
    def __init__(self,
                 W_regularizer=None, u_regularizer=None, b_regularizer=None,
                 W_constraint=None, u_constraint=None, b_constraint=None,
                 bias=True, **kwargs):
 
        self.supports_masking = True
        self.init = initializers.get('glorot_uniform')
 
        self.W_regularizer = regularizers.get(W_regularizer)
        self.u_regularizer = regularizers.get(u_regularizer)
        self.b_regularizer = regularizers.get(b_regularizer)
 
        self.W_constraint = constraints.get(W_constraint)
        self.u_constraint = constraints.get(u_constraint)
        self.b_constraint = constraints.get(b_constraint)
 
        self.bias = bias
        super(HierchacicalAttentionLayer, self).__init__(**kwargs)
 
    def build(self, input_shape):
        assert len(input_shape) == 3
 
        self.W = self.add_weight(shape = (input_shape[-1], input_shape[-1],),
                                 initializer=self.init,
                                 name='{}_W'.format(self.name),
                                 regularizer=self.W_regularizer,
                                 constraint=self.W_constraint)
        if self.bias:
            self.b = self.add_weight(shape = (input_shape[-1],),
                                     initializer='zero',
                                     name='{}_b'.format(self.name),
                                     regularizer=self.b_regularizer,
                                     constraint=self.b_constraint)
 
        self.u = self.add_weight(shape = (input_shape[-1],),
                                 initializer=self.init,
                                 name='{}_u'.format(self.name),
                                 regularizer=self.u_regularizer,
                                 constraint=self.u_constraint)
 
        super(HierchacicalAttentionLayer, self).build(input_shape)
 
    def get_config(self):
        return super(HierchacicalAttentionLayer, self).get_config()
 
    def compute_mask(self, input, input_mask=None):
        # do not pass the mask to the next layers
        return None
 
    def call(self, x, mask=None):
        print('ex',x.shape)
        uit = dot_product(x, self.W)
        print('self.W',self.W.shape)
        if self.bias:
            uit += self.b
        print('self.b',self.b.shape)
        uit = K.tanh(uit)
        print('hx',uit.shape)
        ait = dot_product(uit, self.u)
        print('u',self.u.shape)
        print('a1',ait.shape)
        a = K.exp(ait)
        print('a2',a.shape)
        # apply mask after the exp. will be re-normalized next
        if mask is not None:
            # Cast the mask to floatX to avoid float64 upcasting in theano
            a *= K.cast(mask, K.floatx())
 
        # in some cases especially in the early stages of training the sum may be almost zero
        # and this results in NaN's. A workaround is to add a very small positive number e to the sum.
        # a /= K.cast(K.sum(a, axis=1, keepdims=True), K.floatx())
        a /= K.cast(K.sum(a, axis=1, keepdims=True) + K.epsilon(), K.floatx())
        print('a3',a.shape)
        a = K.expand_dims(a)
        print('a4',a.shape)

        weighted_input = x * a
        print('t',K.sum(weighted_input, axis=1).shape)
        return K.sum(weighted_input, axis=1)
 
    def compute_output_shape(self, input_shape):
        return input_shape[0], input_shape[-1]

In [ ]:
attention3 = HierchacicalAttentionLayer()

In [ ]:
class GraphConvolution2(Layer):
    """Graph convolution layer."""
    def __init__(self, input_dim, output_dim, placeholders, dropout=0.,
                 sparse_inputs=False, act=tf.nn.relu, bias=False,
                 featureless=False, **kwargs):
        super(GraphConvolution2, self).__init__(**kwargs)

        if dropout:
            self.dropout = placeholders['dropout']
        else:
            self.dropout = 0.

        self.act = act
        self.support = placeholders['support']
        self.sparse_inputs = sparse_inputs
        self.featureless = featureless
        self.bias = bias

        # helper variable for sparse dropout
        self.num_features_nonzero = placeholders['num_features_nonzero']

        with tf.variable_scope(self.name + '_vars'):
            for i in range(len(self.support)):
                self.vars['weights_' + str(i)] = glorot([input_dim, output_dim],
                                                        name='weights_' + str(i))
            if self.bias:
                self.vars['bias'] = zeros([output_dim], name='bias')

        if self.logging:
            self._log_vars()

    def _call(self, inputs):
        x = inputs

        # dropout
        if self.sparse_inputs:
            x = sparse_dropout(x, 1-self.dropout, self.num_features_nonzero)
        else:
            x = tf.nn.dropout(x, 1-self.dropout)

        # convolve
        supports = list()
        for i in range(len(self.support)):
            if not self.featureless:
                pre_sup = dot(x, self.vars['weights_' + str(i)],
                              sparse=self.sparse_inputs)
            else:
                pre_sup = self.vars['weights_' + str(i)]
            support = dot(self.support[i], pre_sup, sparse=True)
            supports.append(support)
        output = tf.add_n(supports)

        # bias
        if self.bias:
            output += self.vars['bias']

        return self.act(output)

In [ ]:
#xlm_embds = model.roberta(input_ids, attention_mask=attn_masks)[-1] # 0 -> activation layer (3D), 1 -> pooled output layer (2D) #xlm
#bert_embds = model.bert(input_ids, attention_mask=attn_masks)[1] # 0 -> activation layer (3D), 1 -> pooled output layer (2D)

bert_embds = model.roberta(input_ids, attention_mask=attn_masks)[0] # 0 -> activation layer (3D), 1 -> pooled output layer (2D) #maharoberta
# bert_embds2 = model.roberta(input_ids_emo, attention_mask=attn_masks_emo)[0] # 0 -> activation layer (3D), 1 -> pooled output layer (2D) #maharoberta
#gcn_layer = GraphConvolution2(bert_embds,bert_embds,bert_embds)
#bertcon =  tf.keras.layers.concatenate([bert_embds2,bert_embds])
#intermediate_layer_emo = tf.keras.layers.Flatten(name = 'intermediate_layer_emo')(bert_embds2) #mroberta
# intermediate_layer_emo2 = tf.keras.layers.Dense(768, activation = 'relu', name='intermediate_layer_img_emo2',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(intermediate_layer_emo)
attn_layer = attention3(bert_embds)
# attn_layer2 = attention3(bert_embds2)
# emo_add =  tf.keras.layers.concatenate([attn_layer2,attn_layer])
intermediate_layer = tf.keras.layers.Dense(768, activation='relu', name='intermediate_layer',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(attn_layer)
#intermediate_layer = tf.keras.layers.Dense(256, activation='relu', name='intermediate_layer',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(xlm_embds) #xlm
#intermediate_layer_f = tf.keras.layers.Flatten(name = 'intermediate_layer_f')(intermediate_layer) #xlm
#intermediate_layer_f_2 = tf.keras.layers.Dense(256, activation = 'relu', name='intermediate_layer_img_f_2',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(intermediate_layer_f) #xlm
# intermediate_layer_img = tf.keras.layers.Dense(1000, activation = 'relu', name='intermediate_layer_img',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(img_feats)
# intermediate_layer_img_2 = tf.keras.layers.Dense(256, activation = 'relu', name='intermediate_layer_img_2',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(intermediate_layer_img)
print(type(intermediate_layer))
# concatenate_layer = tf.keras.layers.concatenate([intermediate_layer_f_2,intermediate_layer_img_2]) #xlm
# concatenate_layer = tf.keras.layers.concatenate([intermediate_layer,intermediate_layer_img_2])
intermediate_layer_3 = tf.keras.layers.Dense(512, activation = 'relu', name='intermediate_layer_3',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(intermediate_layer)
intermediate_layer_4 = tf.keras.layers.Dense(256, activation = 'relu', name='intermediate_layer_4',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(intermediate_layer_3)
intermediate_layer_5 = tf.keras.layers.Dense(100, activation = 'relu', name='intermediate_layer_5',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(intermediate_layer_4)
output_layer_1 = tf.keras.layers.Dense(3, activation='softmax', name='output_layer_1',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(intermediate_layer_5) # softmax -> calcs probs of classes
#intermediate_layer_t_1 = tf.keras.layers.Dense(100, activation='relu', name='intermediate_layer_t_1',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(intermediate_layer)
#output_layer_2 = tf.keras.layers.Dense(3, activation='relu', name='output_layer_2',kernel_regularizer = regularizers.l2(0.1),bias_regularizer = regularizers.l2(0.1))(intermediate_layer_t_1)
#output_layer = tf.keras.layers.average([output_layer_1,output_layer_2])

ex (None, 100, 768)
self.W (768, 768)
self.b (768,)
hx (None, 100, 768)
u (768,)
a1 (None, 100)
a2 (None, 100)
a3 (None, 100)
a4 (None, 100, 1)
t (None, 768)
ex (None, 3, 768)
self.W (768, 768)
self.b (768,)
hx (None, 3, 768)
u (768,)
a1 (None, 3)
a2 (None, 3)
a3 (None, 3)
a4 (None, 3, 1)
t (None, 768)
<class 'keras.engine.keras_tensor.KerasTensor'>


In [ ]:
#sentiment_model = tf.keras.Model(inputs=[input_ids, attn_masks,img_feats], outputs=output_layer_1)
sentiment_model = tf.keras.Model(inputs=[input_ids, attn_masks], outputs=[output_layer_1])
# sentiment_model = tf.keras.Model(inputs=[input_ids, attn_masks,input_ids_emo, attn_masks_emo,img_feats], outputs=output_layer_1)

In [ ]:
sentiment_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids_emo (InputLayer)     [(None, 3)]          0           []                               
                                                                                                  
 attention_mask_emo (InputLayer  [(None, 3)]         0           []                               
 )                                                                                                
                                                                                                  
 input_ids (InputLayer)         [(None, 100)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 100)]        0           []                           

In [ ]:
print(intermediate_layer)

KerasTensor(type_spec=TensorSpec(shape=(None, 256), dtype=tf.float32, name=None), name='intermediate_layer/Relu:0', description="created by layer 'intermediate_layer'")


In [ ]:
#optim = tf.keras.optimizers.Adam(learning_rate=1e-5, decay=1e-6)  # lr 5e-5, 3e-5, 2e-5
optim = tf.keras.optimizers.Adam(learning_rate=1e-5, decay=1e-6)  # lr 5e-5, 3e-5, 2e-5
#optim = tf.keras.optimizers.Nadam(learning_rate=1e-5, decay=1e-6)  # lr 5e-5, 3e-5, 2e-5
#optim = tf.keras.optimizers.Adagrad(learning_rate=1e-1, decay=1e-6)
loss_func = tf.keras.losses.CategoricalCrossentropy()
acc = tf.keras.metrics.CategoricalAccuracy('accuracy')

In [ ]:
sentiment_model.compile(optimizer=optim, loss=loss_func, metrics=[acc])

In [ ]:
tqdm_callback = tfa.callbacks.TQDMProgressBar()
hist = sentiment_model.fit(
    #train_dataset,
    dataset,
    validation_data=val_dataset,
    epochs=1,
    shuffle = True
)

ex (6, 3, 768)
self.W (768, 768)
self.b (768,)
hx (6, 3, 768)
u (768,)
a1 (6, 3)
a2 (6, 3)
a3 (6, 3)
a4 (6, 3, 1)
t (6, 768)
ex (6, 100, 768)
self.W (768, 768)
self.b (768,)
hx (6, 100, 768)
u (768,)
a1 (6, 100)
a2 (6, 100)
a3 (6, 100)
a4 (6, 100, 1)
t (6, 768)
ex (6, 3, 768)
self.W (768, 768)
self.b (768,)
hx (6, 3, 768)
u (768,)
a1 (6, 3)
a2 (6, 3)
a3 (6, 3)
a4 (6, 3, 1)
t (6, 768)
ex (6, 100, 768)
self.W (768, 768)
self.b (768,)
hx (6, 100, 768)
u (768,)
a1 (6, 100)
a2 (6, 100)
a3 (6, 100)
a4 (6, 100, 1)
t (6, 768)
4038/4038 [==============================] - ETA: 0s - loss: 129.0053 - accuracy: 0.7775ex (6, 3, 768)
self.W (768, 768)
self.b (768,)
hx (6, 3, 768)
u (768,)
a1 (6, 3)
a2 (6, 3)
a3 (6, 3)
a4 (6, 3, 1)
t (6, 768)
ex (6, 100, 768)
self.W (768, 768)
self.b (768,)
hx (6, 100, 768)
u (768,)
a1 (6, 100)
a2 (6, 100)
a3 (6, 100)
a4 (6, 100, 1)
t (6, 768)
4038/4038 [==============================] - 1042s 251ms/step - loss: 129.0053 - accuracy: 0.7775 - val_loss: 39.3968 - val_ac

In [ ]:
bert_embds[2]

<KerasTensor: shape=(100, 768) dtype=float32 (created by layer 'tf.__operators__.getitem')>

In [ ]:
#  #Evaluate the model on the test data using `evaluate`
# print("Evaluate on test data")
# results = sentiment_model.evaluate(test_dataset, batch_size=batch_size_def)
# print("test loss, test acc:", results)
# #sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

In [ ]:
 #Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = sentiment_model.evaluate(test_dataset_2, batch_size=batch_size_def)
print("test loss, test acc:", results)
#sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

Evaluate on test data
250/250 [==============================] - 12s 47ms/step - loss: 39.3990 - accuracy: 0.8347
test loss, test acc: [39.399009704589844, 0.8346666693687439]


In [ ]:
counter =0

In [ ]:
# Generate a prediction using model.predict() 
# and calculate it's shape:
print("Generate a prediction")
prediction = sentiment_model.predict(test_dataset_2,batch_size=batch_size_def)
print("prediction shape:", prediction.shape)
pred_f = np.zeros(1500)
for i in range(1500):
  if prediction[i][0]>prediction[i][1] and prediction[i][0]>prediction[i][2]:
    pred_f[i] = 0
  elif prediction[i][1]>prediction[i][0] and prediction[i][1]>prediction[i][2]:
    pred_f[i] = 1
  else:
    pred_f[i] = 2
print("prediction shape:", prediction)
np.save('/content/gdrive/My Drive/image download/pred'+str(counter)+'_valid.npy',pred_f)
counter +=1

Generate a prediction
250/250 [==============================] - 11s 44ms/step
prediction shape: (1500, 3)
prediction shape: [[0.12185905 0.22864519 0.6494958 ]
 [0.07011906 0.73436606 0.19551484]
 [0.07217471 0.7485683  0.1792571 ]
 ...
 [0.8449898  0.07864425 0.07636604]
 [0.0856869  0.74507517 0.16923796]
 [0.18909535 0.17789695 0.6330077 ]]


In [ ]:
tqdm_callback = tfa.callbacks.TQDMProgressBar()
hist = sentiment_model.fit(
    #train_dataset,
    dataset,
    validation_data=val_dataset,
    epochs=1,
    shuffle = True
)

4038/4038 [==============================] - 1008s 250ms/step - loss: 15.3838 - accuracy: 0.8031 - val_loss: 4.3960 - val_accuracy: 0.8333


In [ ]:
#  #Evaluate the model on the test data using `evaluate`
# print("Evaluate on test data")
# results = sentiment_model.evaluate(test_dataset, batch_size=batch_size_def)
# print("test loss, test acc:", results)
# #sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

In [ ]:
 #Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = sentiment_model.evaluate(test_dataset_2, batch_size=batch_size_def)
print("test loss, test acc:", results)
#sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

Evaluate on test data
250/250 [==============================] - 12s 47ms/step - loss: 4.3974 - accuracy: 0.8327
test loss, test acc: [4.397424697875977, 0.8326666951179504]


In [ ]:
# Generate a prediction using model.predict() 
# and calculate it's shape:
print("Generate a prediction")
prediction = sentiment_model.predict(test_dataset_2,batch_size=batch_size_def)
print("prediction shape:", prediction.shape)
pred_f = np.zeros(1500)
for i in range(1500):
  if prediction[i][0]>prediction[i][1] and prediction[i][0]>prediction[i][2]:
    pred_f[i] = 0
  elif prediction[i][1]>prediction[i][0] and prediction[i][1]>prediction[i][2]:
    pred_f[i] = 1
  else:
    pred_f[i] = 2
print("prediction shape:", prediction)
np.save('/content/gdrive/My Drive/image download/pred'+str(counter)+'_valid.npy',pred_f)
counter +=1

Generate a prediction
250/250 [==============================] - 11s 44ms/step
prediction shape: (1500, 3)
prediction shape: [[0.19007356 0.24917011 0.5607563 ]
 [0.08502398 0.729617   0.18535902]
 [0.08527137 0.73444086 0.18028781]
 ...
 [0.84025824 0.08201231 0.07772945]
 [0.1004982  0.72482944 0.17467235]
 [0.18342552 0.17851779 0.6380567 ]]


In [ ]:
tqdm_callback = tfa.callbacks.TQDMProgressBar()
hist = sentiment_model.fit(
    #train_dataset,
    dataset,
    validation_data=val_dataset,
    epochs=1,
    shuffle = True
)

4038/4038 [==============================] - 1012s 251ms/step - loss: 1.3116 - accuracy: 0.8906 - val_loss: 1.2193 - val_accuracy: 0.8302


In [ ]:
#  #Evaluate the model on the test data using `evaluate`
# print("Evaluate on test data")
# results = sentiment_model.evaluate(test_dataset, batch_size=batch_size_def)
# print("test loss, test acc:", results)
# #sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

In [ ]:
 #Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = sentiment_model.evaluate(test_dataset_2, batch_size=batch_size_def)
print("test loss, test acc:", results)
#sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

Evaluate on test data
250/250 [==============================] - 12s 46ms/step - loss: 1.2230 - accuracy: 0.8240
test loss, test acc: [1.2229831218719482, 0.8240000009536743]


In [ ]:
# Generate a prediction using model.predict() 
# and calculate it's shape:
print("Generate a prediction")
prediction = sentiment_model.predict(test_dataset_2,batch_size=batch_size_def)
print("prediction shape:", prediction.shape)
pred_f = np.zeros(1500)
for i in range(1500):
  if prediction[i][0]>prediction[i][1] and prediction[i][0]>prediction[i][2]:
    pred_f[i] = 0
  elif prediction[i][1]>prediction[i][0] and prediction[i][1]>prediction[i][2]:
    pred_f[i] = 1
  else:
    pred_f[i] = 2
print("prediction shape:", prediction)
np.save('/content/gdrive/My Drive/image download/pred'+str(counter)+'_valid.npy',pred_f)
counter +=1

Generate a prediction
250/250 [==============================] - 11s 44ms/step
prediction shape: (1500, 3)
prediction shape: [[0.0864839  0.3440733  0.5694428 ]
 [0.08007216 0.7679273  0.15200058]
 [0.0801165  0.7670798  0.15280372]
 ...
 [0.8690106  0.06954838 0.06144105]
 [0.0804068  0.76331365 0.15627949]
 [0.1470886  0.16440494 0.6885064 ]]


In [ ]:
tqdm_callback = tfa.callbacks.TQDMProgressBar()
hist = sentiment_model.fit(
    #train_dataset,
    dataset,
    validation_data=val_dataset,
    epochs=1,
    shuffle = True
)

4038/4038 [==============================] - 1011s 250ms/step - loss: 0.9449 - accuracy: 0.9112 - val_loss: 1.0841 - val_accuracy: 0.8222


In [ ]:
#  #Evaluate the model on the test data using `evaluate`
# print("Evaluate on test data")
# results = sentiment_model.evaluate(test_dataset, batch_size=batch_size_def)
# print("test loss, test acc:", results)
# #sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

In [ ]:
 #Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = sentiment_model.evaluate(test_dataset_2, batch_size=batch_size_def)
print("test loss, test acc:", results)
#sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

Evaluate on test data
250/250 [==============================] - 12s 46ms/step - loss: 1.0799 - accuracy: 0.8247
test loss, test acc: [1.0799355506896973, 0.8246666789054871]


In [ ]:
# Generate a prediction using model.predict() 
# and calculate it's shape:
print("Generate a prediction")
prediction = sentiment_model.predict(test_dataset_2,batch_size=batch_size_def)
print("prediction shape:", prediction.shape)
pred_f = np.zeros(1500)
for i in range(1500):
  if prediction[i][0]>prediction[i][1] and prediction[i][0]>prediction[i][2]:
    pred_f[i] = 0
  elif prediction[i][1]>prediction[i][0] and prediction[i][1]>prediction[i][2]:
    pred_f[i] = 1
  else:
    pred_f[i] = 2
print("prediction shape:", prediction)
np.save('/content/gdrive/My Drive/image download/pred'+str(counter)+'_valid.npy',pred_f)
counter +=1

Generate a prediction
250/250 [==============================] - 11s 44ms/step
prediction shape: (1500, 3)
prediction shape: [[0.14845604 0.1880328  0.66351116]
 [0.08076996 0.7773088  0.14192125]
 [0.08004388 0.7707085  0.14924759]
 ...
 [0.86758894 0.07012247 0.06228862]
 [0.08014753 0.76879454 0.15105788]
 [0.12359056 0.14740084 0.7290086 ]]


In [ ]:
tqdm_callback = tfa.callbacks.TQDMProgressBar()
hist = sentiment_model.fit(
    #train_dataset,
    dataset,
    validation_data=val_dataset,
    epochs=1,
    shuffle = True
)

4038/4038 [==============================] - 1009s 250ms/step - loss: 0.8358 - accuracy: 0.9259 - val_loss: 1.0827 - val_accuracy: 0.8084


In [ ]:
#  #Evaluate the model on the test data using `evaluate`
# print("Evaluate on test data")
# results = sentiment_model.evaluate(test_dataset, batch_size=batch_size_def)
# print("test loss, test acc:", results)
# #sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

In [ ]:
 #Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = sentiment_model.evaluate(test_dataset_2, batch_size=batch_size_def)
print("test loss, test acc:", results)
#sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_10epo_batch15_regularization_lr1e-5')

Evaluate on test data
250/250 [==============================] - 12s 46ms/step - loss: 1.0598 - accuracy: 0.8180
test loss, test acc: [1.0597714185714722, 0.8180000185966492]


In [ ]:
# Generate a prediction using model.predict() 
# and calculate it's shape:
print("Generate a prediction")
prediction = sentiment_model.predict(test_dataset_2,batch_size=batch_size_def)
print("prediction shape:", prediction.shape)
pred_f = np.zeros(1500)
for i in range(1500):
  if prediction[i][0]>prediction[i][1] and prediction[i][0]>prediction[i][2]:
    pred_f[i] = 0
  elif prediction[i][1]>prediction[i][0] and prediction[i][1]>prediction[i][2]:
    pred_f[i] = 1
  else:
    pred_f[i] = 2
print("prediction shape:", prediction)
np.save('/content/gdrive/My Drive/image download/pred'+str(counter)+'_valid.npy',pred_f)
counter +=1

Generate a prediction
250/250 [==============================] - 11s 45ms/step
prediction shape: (1500, 3)
prediction shape: [[0.12747823 0.19115014 0.6813717 ]
 [0.06844322 0.8127251  0.11883167]
 [0.06837472 0.8127428  0.11888242]
 ...
 [0.87522054 0.06480794 0.05997157]
 [0.06853738 0.81079084 0.12067177]
 [0.13474506 0.16546844 0.6997865 ]]


In [ ]:
abcd hjjhvhjnbnhgmvch
efghihhmjdjftmghhgbhhhhj

SyntaxError: ignored

In [ ]:
#sentiment_model.save('/content/gdrive/My Drive/saved models/xlm-roberta-base_012_img_30epo_batch15_regularization_lr1e-5_layer9')

In [ ]:
# PREDICTION
'''
sentiment_model = tf.keras.models.load_model('sentiment_model')

tokenizer = AlbertTokenizer.from_pretrained('ai4bharat/indic-bert')

def prepare_data(input_text, tokenizer):
    token = tokenizer.encode_plus(
        input_text,
        max_length=128, 
        truncation=True, 
        padding='max_length', 
        add_special_tokens=True,
        return_tensors='tf'
    )
    return {
        'input_ids': tf.cast(token.input_ids, tf.float64),
        'attention_mask': tf.cast(token.attention_mask, tf.float64)
    }

def make_prediction(model, processed_data, classes=['Negative','Neutral','Positive']):
    probs = model.predict(processed_data)[0]
    return classes[np.argmax(probs)]
input_text = input('Enter movie review here: ')
processed_data = prepare_data(input_text, tokenizer)
result = make_prediction(sentiment_model, processed_data=processed_data)
print(f"Predicted Sentiment: {result}")
'''