In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
!pip install keras_preprocessing

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
import re
import collections
import tensorflow as tf
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from keras.preprocessing.text import Tokenizer
from keras_preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from keras import models
from keras import layers

In [ ]:
x2 = np.load('/content/gdrive/My Drive/image download/features_3_train.npy')
# x3 = np.load('/content/gdrive/My Drive/image download/features_3_test.npy')
# x4 = np.load('/content/gdrive/My Drive/image download/features_3_valid.npy')

In [ ]:
X_img_features = np.zeros((len(df), 1000))
# X_img_features_f_val = np.zeros((len(df), 1000))
# X_img_features_f_test = np.zeros((len(df), 1000))

In [ ]:
for i in range(len(df)):
  X_img_features[i] = x2[i]
# for i in range(len(df2)):
#   X_img_features_val[i] = x3[i]
# for i in range(len(df3)):
#   X_img_features_test[i] = x4[i]

In [ ]:
zer=0
nzer=0

In [ ]:
z = np.zeros(1000)

In [ ]:
X_img_features[0].shape

(1000,)

In [ ]:
for i in range(12114):
    if X_img_features[i][0] != 0 or X_img_features[i][1] != 0 or X_img_features[i][10] != 0:
      nzer+=1
    else: 
      zer+=1

In [ ]:
nzer

4161

In [ ]:
fin_lab=[]
fin_fea=np.zeros((4161,1000))

In [ ]:
j=0
for i in range(12114):
    if X_img_features[i][0] != 0:
      fin_fea[j] = X_img_features[i]
      fin_lab.append(int(df['label'][i]))
      j+=1

In [ ]:
len(fin_lab)

4161

In [ ]:
X_img_features.shape

(12114, 1000)

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/dataset/tweets-train_pp_stop_012.csv')
#df = df.reindex(np.random.permutation(df.index))
# df = df[['tweet', 'label','bal']]
# df.text = df.text.apply(remove_stopwords).apply(remove_mentions)
#X_train, X_test, y_train, y_test = train_test_split(df.text, df.airline_sentiment, test_size=0.1, random_state=37)

In [ ]:
x2.shape

(24228, 1, 1000)

In [ ]:
# i = 8818
# print(df['label'][i],df['tweet'][i])

In [ ]:
le = LabelEncoder()
y_train_le = le.fit_transform(fin_lab)
#y_test_le = le.transform(y_test)
y_train_oh = to_categorical(y_train_le)
#y_test_oh = to_categorical(y_test_le)

In [ ]:
#y_train_oh[3]

In [ ]:
# X_train, X_test, y_train, y_test = train_test_split(df.tweet, df.label, test_size=0.1, random_state=37)
X_train, X_test, y_train, y_test = train_test_split(fin_fea, y_train_oh, test_size=0.1, random_state=37)

In [ ]:
#del(tweet_emb)

In [ ]:
#X_train,y_train

In [ ]:
#y_test

In [ ]:
#y_test_oh

In [ ]:
# #le = LabelEncoder()
# #y_train_le = le.fit_transform(df['label'])
# y_test_le = le.transform(y_test)
# #y_train_oh = to_categorical(y_train_le)
# y_test_oh = to_categorical(y_test_le)

In [ ]:
#X_train_emb, X_valid_emb, y_train_emb, y_valid_emb = train_test_split(X_train, y_train, test_size=0.1, random_state=37)

In [ ]:
optim = tf.keras.optimizers.legacy.Adam(learning_rate=1e-5, decay=1e-6)  # lr 5e-5, 3e-5, 2e-5
#optim = tf.keras.optimizers.Nadam(learning_rate=1e-5, decay=1e-6)  # lr 5e-5, 3e-5, 2e-5
#optim = tf.keras.optimizers.Adam(learning_rate=1e-5)  # lr 5e-5, 3e-5, 2e-5
loss_func = tf.keras.losses.CategoricalCrossentropy()
acc = tf.keras.metrics.CategoricalAccuracy('accuracy')

In [ ]:
emb_model = models.Sequential()
#emb_model.add(layers.Embedding(49795, 8, input_length=50))
emb_model.add(layers.Flatten())
#emb_model.add(layers.Dense(8000, activation='relu'))
#emb_model.add(layers.Dense(4000, activation='relu'))
#emb_model.add(layers.Dense(2000, activation='relu'))
#emb_model.add(layers.Dense(1000, activation='relu'))
emb_model.add(layers.Dense(500, activation='relu'))
emb_model.add(layers.Dense(100, activation='relu'))
emb_model.add(layers.Dense(3, activation='softmax'))
emb_model.compile(loss=loss_func, optimizer=optim, metrics=acc)

In [ ]:
emb_model.layers

In [ ]:
#emb_model.summary()

In [ ]:
history = emb_model.fit(fin_fea, y_train_oh,validation_split=0.1, epochs=10,batch_size=4)

Epoch 1/10
936/936 [==============================] - 7s 6ms/step - loss: 1.0882 - accuracy: 0.4148 - val_loss: 1.0810 - val_accuracy: 0.4245
Epoch 2/10
936/936 [==============================] - 8s 9ms/step - loss: 1.0777 - accuracy: 0.4249 - val_loss: 1.0707 - val_accuracy: 0.4532
Epoch 3/10
936/936 [==============================] - 10s 10ms/step - loss: 1.0702 - accuracy: 0.4455 - val_loss: 1.0632 - val_accuracy: 0.4580
Epoch 4/10
936/936 [==============================] - 10s 11ms/step - loss: 1.0649 - accuracy: 0.4546 - val_loss: 1.0577 - val_accuracy: 0.4676
Epoch 5/10
936/936 [==============================] - 6s 7ms/step - loss: 1.0610 - accuracy: 0.4549 - val_loss: 1.0536 - val_accuracy: 0.4580
Epoch 6/10
936/936 [==============================] - 7s 7ms/step - loss: 1.0578 - accuracy: 0.4615 - val_loss: 1.0501 - val_accuracy: 0.4604
Epoch 7/10
936/936 [==============================] - 5s 5ms/step - loss: 1.0548 - accuracy: 0.4637 - val_loss: 1.0467 - val_accuracy: 0.4628
Ep

In [ ]:
# results = emb_model.evaluate(X_test,y_test, batch_size=6)
results = emb_model.evaluate(fin_fea,y_train_oh, batch_size=4)
print("test loss, test acc:", results)

1041/1041 [==============================] - 4s 4ms/step - loss: 1.0433 - accuracy: 0.4785
test loss, test acc: [1.0433282852172852, 0.4784907400608063]


In [ ]:
print("Generate a prediction")
prediction = emb_model.predict(fin_fea,4)
print("prediction shape:", prediction.shape)
pred_f = np.zeros(4161)
for i in range(4161):
  if prediction[i][0]>prediction[i][1] and prediction[i][0]>prediction[i][2]:
    pred_f[i] = 0
  elif prediction[i][1]>prediction[i][0] and prediction[i][1]>prediction[i][2]:
    pred_f[i] = 1
  else:
    pred_f[i] = 2
print("prediction shape:", prediction)
np.save('/content/gdrive/My Drive/image download/47.84pred_img_0.1split.npy',pred_f)
np.save('/content/gdrive/My Drive/image download/pred_img_0.1splitlabels.npy',fin_lab)
# counter +=1

Generate a prediction
1041/1041 [==============================] - 4s 4ms/step
prediction shape: (4161, 3)
prediction shape: [[0.2650387  0.32027113 0.41469017]
 [0.20431724 0.2888625  0.50682026]
 [0.23695219 0.3391951  0.42385265]
 ...
 [0.2620201  0.35444093 0.3835389 ]
 [0.26529774 0.3537986  0.38090375]
 [0.24166185 0.35976192 0.39857626]]


In [ ]:
emb_results = test_model(emb_model, X_train, y_train, X_test, y_test, 6)
print('/n')
print('Test accuracy of word embeddings model: {0:.2f}%'.format(emb_results[1]*100))

NameError: ignored